### ISSUE TITLE
The result of evaluting with KITTI native codes is 0

### ISSUE THREAD

**Issue by ZhangK9509** [wwooo/tensorflow_complex_yolo#2]
Hello, thank you for provided so a great work. I have trained the model with default cofig and then evaluated the final checkpoint using KITTI native codes. There is a IOERROR that the path of weight should be provided not using the default path. The result of evaluating is all of APs are 0. Is there something wrong? Or it needs more steps when training?

**Comment by DarkNetUsr** [comment]
You should run the predict.py  first and determine if the predicted result is normal. The model actually converges pretty well in about 60,000 steps.

**Comment by DarkNetUsr** [comment]
@ZhangK9509 You should run the predict.py first and determine if the predicted result is normal. In fact, the model converges pretty well at about 6,0000 steps.

**Comment by Hizhaoyuan** [comment]
Hi , you should run the predict.py first and determine if the predicted result is normal. In fact, the model converges pretty well at about 6,0000 steps. If you have any more questions, please feel free to ask.

**Comment by ZhangK9509** [comment]
I have trained with 60,000 steps. The prediction results look great. But when evaluating, the results still is zero. I complie the `evaluate_object_3d_offline.cpp`, make the directories `60000/data` and move evaluation results by `kitti_eval.py` in `eval_result` to `60000/data`. The command is `./evaluate_object_3d_offline /home/rv/Kitti/object/training/label_2 60000`. Is something wrong with me?

**Comment by Hizhaoyuan** [comment]
Since the output result is not complete, we need to change the internal logic of the evaluation script. I can give you the version I used, and you can make changes according to your needs. In fact, the official kitti evaluation code is quite long and you should study it carefully.

**Comment by ZhangK9509** [comment]
Thank you. It is kind of you to share your version with me. This is my email painter9509@126.com.

**Comment by Hizhaoyuan** [comment]
I have sent it to your mailbox.

**Comment by ZhangK9509** [comment]
Thank you very much!
